from django.urls import path
from . import views
urlpatterns = [
    path('', views.main),
    path('admin_home', views.admin_home),
    path('approve_advocate', views.approve_advocate),
    path('manage_court_details', views.manage_court_details),
    path('manage_court_details', views.manage_court_details),
    path('add_new_court', views.add_new_court),
    path('manage_dataset', views.manage_dataset),
    path('add_dataset', views.add_dataset),
    path('manage_section', views.manage_section),
    path('add_new_section', views.add_new_section),
    path('view_complaint', views.view_complaint),
    path('reply/<int:id>', views.reply),
    path('acceptad/<int:id>', views.acceptad),
    path('delet/<int:id>', views.delet),
    path('add_sctnqstns', views.add_sctnqstns),
    path('sectioninfoo', views.sectioninfoo),
    path('advstatus', views.advstatus),
    path('advstatuscode', views.advstatuscode),
    path('ManageEvidence/<int:id>', views.ManageEvidence,name="ManageEvidence"),
    path('ManageNotification/<int:id>', views.ManageNotification, name="ManageNotification"),
    path('Notification', views.Notification, name="Notification"),
    path('addnotif', views.addnotif, name="addnotif"),
    path('eviden', views.eviden, name="eviden"),
    path('addevid', views.addevid, name="addevid"),
    path('evidencee', views.evidencee, name="evidencee"),
    path('get_question', views.get_question, name="get_question"),
    path('psections', views.psections, name="psections"),
    path('answertest', views.answertest, name="answertest"),
    path('bstatus', views.bstatus, name="bstatus"),
    path('view_advocate_recom', views.view_advocate_recom, name="view_advocate_recom"),

    path('rejectad/<int:id>', views.rejectad),
    path('blocked/<int:id>', views.blocked),
    path('unblocked/<int:id>', views.unblocked),
    path('dlt_ds/<int:id>', views.dlt_ds),
    path('delete/<int:id>', views.delete),
    path('acceptbooking/<int:id>', views.acceptbooking),
    path('rejectbooking/<int:id>', views.rejectbooking),
    path('feedback', views.feedback),
    path('Block_advocate', views.Block_advocate),
    path('reply_code', views.reply_code),
    path('Advocate_Registration', views.Advocate_Registration),
    path('Advocate_Home', views.Advocate_Home),
    path('View_booking', views.View_booking),
    path('acceptbooking', views.acceptbooking),
    path('Add_hearing_dates/<int:id>', views.Add_hearing_dates),
    path('Manage_hearing_dates', views.Manage_hearing_dates),
    path('View_payment_history', views.View_payment_history),
    path('logincode', views.logincode),
    path('advocatecode', views.advocatecode),
    path('courtcode', views.courtcode),
    path('sectioncode', views.sectioncode),
    path('datasetcode', views.datasetcode),
    path('edit_court/<int:id>', views.edit_court),
    path('editcode',views.editcode,name='editcode'),
    path('searchapprove_advocate', views.searchapprove_advocate),
    path('Search_Block_advocate', views.Search_Block_advocate),
    path('View_booking', views.View_booking),
    path('Manage_hearing_dates', views.Manage_hearing_dates),
    path('View_payment_history', views.View_payment_history),
    path('hearingcode', views.hearingcode),
    path('logout', views.logout),



    path('chatwithuser', views.chatwithuser, name='chatwithuser'),
    path('chatview', views.chatview, name='chatview'),
    path('coun_msg/<int:id>', views.coun_msg, name='coun_msg'),
    path('coun_insert_chat/<str:msg>/<int:id>', views.coun_insert_chat, name='coun_insert_chat'),
    path('section_question', views.section_question),
    path('case_dataset', views.case_dataset),
    path('questioncode', views.questioncode),
    path('manage_case_section_question', views.manage_case_section_question),
    path('dele/<int:id>', views.dele),

    # %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% web-service%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

    path('logincodess', views.logincodess,name="logincodess"),
    path('search_section1', views.search_section1,name="search_section1"),
    path('registration', views.registration),
    path('hearing_details', views.hearing_details),
    path('sendfeedback', views.sendfeedback),
    path('complaint_user', views.complaint_user),
    path('view_reply_comp', views.view_reply_comp),
    path('view_feedback', views.view_feedback),
    path('view_section_info', views.view_section_info),
    path('view_advocate_info', views.view_advocate_info),
    path('court_details', views.court_details),
    path('search_section', views.search_section),
    path('view_advocate_infoo', views.view_advocate_infoo),
    path('booking_advocate', views.booking_advocate),
    path('chat', views.chat),
    path('in_message2', views.in_message2),
    path('in_message2', views.in_message2),
    path('view_message2', views.view_message2),
    path('court_details2', views.court_details2),
    path('notificationn', views.notificationn),
    path('paymentfinish', views.paymentfinish),




]
